[project]
name = "small-language-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.6.0",
    "ipykernel>=6.29.5",
    "tiktoken>=0.9.0",
    "torch>=2.7.1",
]
